{% set version = "1.8.1" %}

package:
  name: django-redis-cache
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/django-redis-cache/django-redis-cache-{{ version }}.tar.gz
  sha256: d87bbc3d92a39a079bc31a290df9caba8487d37a02981def31168e39845031e8

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - django
    - redis-py >=2.10.3
  run:
    - python
    - django
    - redis-py >=2.10.3

test:
  imports:
    - redis_cache

about:
  home: http://github.com/sebleier/django-redis-cache/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'Redis Cache Backend for Django'

extra:
  recipe-maintainers:
    - kwilcox
