{% set version = "2.0.0" %}

package:
  name: django-redis-cache
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/django-redis-cache/django-redis-cache-{{ version }}.tar.gz
  sha256: 77dcb9d11beef5ce77dadfb95328b7712c3d9bde8419a0ba92968712b9bff48b

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - python
    - pip
    - django
    - redis-py >=2.10.3
  run:
    - python
    - django
    - redis-py >=2.10.3

test:
  imports:
    - redis_cache

about:
  home: http://github.com/sebleier/django-redis-cache/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'Redis Cache Backend for Django'

extra:
  recipe-maintainers:
    - kwilcox
