{% set version = "2.1.3" %}

package:
  name: django-redis-cache
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/d/django-redis-cache/django-redis-cache-{{ version }}.tar.gz
  sha256: e72691539be99c0b2dd64ac380e26f4d2be5c53c1b2d26845dd279ae38b47477

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - django
    - redis-py <4.0
    - six

test:
  imports:
    - redis_cache
    - redis_cache.backends
  commands:
    - pip check
  requires:
    - pip


about:
  home: http://github.com/sebleier/django-redis-cache/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Redis Cache Backend for Django

extra:
  recipe-maintainers:
    - kwilcox
