travis:
  secure:
    BINSTAR_TOKEN: lXTk+elVzaLoAeARrjT3jnOPQxqKqsZj/LlvsGEc5dVaurftptvkBAOxz3XU6WlnAIXAxfgCmKOSk6fjzs5WxO3rPYIa3x0p3QfrOALEZcxtUv8MIwfF6m6n8cVqb86+jQ8AS/s1YD12oPIBJmoS1N4s9mhvKjlFyUlVfl22F4XtWxFqneVAFLd7mxelNJasBkGGAOnT5xEiXFgHkg4g2ZAJT5D/ni8VwIpusbT4KQ542lAFDfbZTEQ2g6DrAPZyefJ2r79M4AhiRRe3tO/WY79x1qYFXY7PvJohCcCTTj/kRI7jEC6KNVsxlgfFN/OfiJD7DF6rk6vL7rXi5ktZ54Rggw1WskHTr7XpkmAesFYTROJuX3IUbewjqdLulFGepfipubYbaLUA/cgRDct2HgakbCDIefK/d+SiLrN7a26LnCQzPxEb6R5Z4bHJ7P6UBm8USIY3O/55MQ2WyN50b5yyFSHd4bOtDQO99GAjT6tcAO/VwYJCm/K3ArVswQSG0fpsNsIh9NtwtfqXRbbz/eHd7SzupV5ybpqQBttS6iZZ83TYnDscd03HKzvl3iteI0Nj5wVCCJWZyVhgAosNrQPch718EdUMlv1uegQtWadU/XDJK7azhBZ3iZIFdu87MEdxFRkJoNNUmaEZMsgbPpG7Kf3ktuAcSXKm+QZn6+k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
