travis:
  secure:
    BINSTAR_TOKEN: afR+za30CRJbraeUpZIXfbFY5DwipPbYUwNHGMHjU+k85YNpAL17/wvUlKGq7tCZGrbS6HeEPH9Z1Ezsuku1XYjQ0CHomWepXCuXUCXca8FLFnoXosUjcuzpGYi8EFovN+lx8U1kZykPgcwdy93xFYIYLXLcXmTdVwzCWJqN+j7wgvKA4QJ15zp/Cs7aF5TNz9sms39avmjPpbwfCetscuP0T1QPXMnKTCS8fKMbKy4GXh89P/0X+bqm7TeogMcvkBf8y8VqGO/tznL/uKSWCyXClbSYZO0ihZyPXL88D+0ZDSqeEwyzRll2V45wyopdZqzsn7hgeac8VVdxkP0HkAad1HWA/ca0c87WM3MgFjZnLYtiG8DYeQWaRLitm44NPI25w1gHb4yz0SULQ691K0gkl1aoHo6z0CwIKpdRVXE1bxygbyPYZixpA6sbiC296nunYymP7d5oJGQY2NrazXn2urD09Ll8OoWqd+84roSjd1O77DA/0pCbMhP8dGJ44eOOLK8j4W2Np+KN9lCwyBC1UW9WQ7CN8eXXTXlG35a8S1TWV9vXO/szv59Z3CZ3LfS2Iy0omo6gSOxVZCGXgnz2hxFUQt9C8Tbke+T2/7kLccBuHTVejkqzIgavniXxXjph7vhJNZvrF5FBkXeD9EbWzKbiEqNzknMFwiI1e/Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
