travis:
  secure:
    BINSTAR_TOKEN: I906OPbHrnNzptg5jChRJCOt4t3CR+JvJYVumSALb3TR2bD3WBqE3LQUf9H9q9i6DcA3jPpCCOM4PSYTiTatT72euXdQkO8+1XrEeQH4kSVb9EMpO0sVXmRKS3VFBYuO2IKD+/GCL/+yEun6C+Z7A39k0GemxsDy5q0uUE3NGS8Yzq+4TXZfNNokmOF5AClVsYRPX6+RJRBfCilcXN7RhNKNzGc/Z1Fdka+ayGF1JAZPuewEE0A8eo8ieiDKb5TBLt1Lbuebes5gIgeM/9j9tmi8j29T/xMD+PwJ6y9DlQmsaAqzs4tbKCFJD4ZWKpxcH7zxZQIjsBf1iT3+Wzbt7Dkum04LWItXge3tamvV/HH/BZHGOfRJQcceFJ18XY5OTGviZaUaMf4Vfe8T5mygFxiljW1fO9Iqo26p7fMhnSwysVpzFW9wR4eu4ghRIlTh+4Ygs0VyR3eI6qYAyv8cRWvJP4VW0IsqaRI3ncPwimxyR0GTjXz/u65cKVt0iNQMVtSYvqNMN+uXYOaka3lAf4Xanmf/VIejpq8IQhxrXZyOMS0UjbuYB8hPSxWbCHgBdDrNU8mD4rU89WDvNh8uMEzlKAq2ZpbiG3sd2nsTIoy2nObg+qjI4yDKdMGw7UtJq1PydqbQGIAyzVbxGRquvankrHDTCst71Gw/vrgiLo0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
